INSERT INTO `tb_students` (`sid`, `stu_num`, `stu_name`, `stu_gender`, `stu_age`) VALUES (1, '00001', '张三', '男', 18);
INSERT INTO `tb_students` (`sid`, `stu_num`, `stu_name`, `stu_gender`, `stu_age`) VALUES (2, '1001', '张三', '男', 21);
INSERT INTO `tb_students` (`sid`, `stu_num`, `stu_name`, `stu_gender`, `stu_age`) VALUES (6, '10010', '王五', '女', 18);
INSERT INTO `tb_students` (`sid`, `stu_num`, `stu_name`, `stu_gender`, `stu_age`) VALUES (4, '10005', '张三', '男', 21);
INSERT INTO `tb_students` (`sid`, `stu_num`, `stu_name`, `stu_gender`, `stu_age`) VALUES (5, '10009', '张三', '男', 21);
INSERT INTO `tb_students` (`sid`, `stu_num`, `stu_name`, `stu_gender`, `stu_age`) VALUES (7, '10011', '张三', '男', 21);
INSERT INTO `tb_students` (`sid`, `stu_num`, `stu_name`, `stu_gender`, `stu_age`) VALUES (8, '10012', '张三里斯', '男', 29);
INSERT INTO `tb_students` (`sid`, `stu_num`, `stu_name`, `stu_gender`, `stu_age`) VALUES (9, '10013', '张三里斯王五', '男', 29);
INSERT INTO `tb_students` (`sid`, `stu_num`, `stu_name`, `stu_gender`, `stu_age`) VALUES (10, '10014', '张三里斯王五', '男', 29);
